# Generated by Django 3.0.8 on 2020-07-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermDepositAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='campaign_contacts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='last_contact_day_of_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='last_contact_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='num_days_passed_after_campaign_comtact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='previous_contact_before_campaign',
            field=models.IntegerField(default=0),
        ),
    ]
