# Generated by Django 3.0.8 on 2020-07-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermDepositAPI', '0002_auto_20200715_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='default',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='last_contact_day_of_the_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='last_contact_duration_in_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='number_of_contacts_during_campaign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='number_of_days_passed_after_campaign_contact',
            field=models.IntegerField(default=0),
        ),
    ]
